server:
  port: 8304

spring:
  application:
    name: zuul-proxy
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    registerWithEureka: false
    fetchRegistry: false    

zuul:
  prefix: /api
  routes:
    fxrate-service:
      path: /fxrate-service/**
      url: http://localhost:8302
    fxrate-db-service:
      path: /fxrate-db/**
      url: http://localhost:8301    
    